### ISSUE TITLE
Reuse of code & Integration into Bullet Physics Browser

### ISSUE THREAD

**Issue by benelot** [matpalm/cartpoleplusplus#2]
Hello Mat,

A common friend of ours (Erwin) sent me your way for an example on how to use pybullet, setup some gym environment and use tensorflow for learning. I recently published a 3DNNWalker example to the Bullet Physics Example Browser, so far still using the Bullet 2.x API. It trains a one layer NN using evolutionary algorithms to make spiders walk. As I intend to rebuild it from scratch with pybullet and tensorflow to teach it to walk in a different way, I would like to take your setup as an example. 

-Do you care if I reuse some of your code for my learning example?

-Are you interested in creating a pull request of this example to the browser?

-Can I ask you more questions in case I stumble with my own example?

In case you want a more private discussion, here is my mail adress: be.ellenberger@gmail.com.

**Comment by matpalm** [comment]
erwin showed me your example the other day, looks cool! funnily enough evolving neural networks was my uni research topic back in the 90s!

feel free to grab whatever you like, i'll try to answer any questions you have. have no time to port it in any way though, so little bit time these days :(
